### ISSUE TITLE
Issue with special character

### ISSUE THREAD

**Issue by jdelgado111** [Xonshiz/Hulu-Subs-Downloader#22]
![issue](https://user-images.githubusercontent.com/31085648/103994042-4fe90380-514b-11eb-9d2c-e688ae6bbf62.JPG)

On Windows 10, it looks like there's an issue when trying to download subtitles from something that has a special character in the title. Seems to be an issue when it tries to create the folder, it adds the special character which isn't allowed. The tool worked correctly when I tried it on another series that didn't have the ":" special character.

**Comment by Xonshiz** [comment]
Oh damn, totally forgot about the special characters. Thanks for bringing this up. Could you please share the URL for the video/show as well, so that I can take a look and fix this one.

**Comment by jdelgado111** [comment]
Ah sorry I'm away from my computer now, but the URL and name of the series is in the screenshot above. Tomorrow I can add the URL here directly for convenience.

**Comment by Xonshiz** [comment]
Yes, that would be better if you could just post it out here. I'll get a fix ready meanwhile.

**Comment by Xonshiz** [comment]
I've pushed the update. I checked with some other video with special characters. It was downloading fine. Please do download the latest binary again and verify that it's downloading for you now :)

**Comment by jdelgado111** [comment]
Looks like it's still not working for me even with the update. I get this error in the log:

DEBUG: HuluException: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\jdm41\\Downloads\\Ghost in the Shell: Stand Alone Complex\\1'

The special character is still being included in the folder name.

Here's the episode link I'm using: https://www.hulu.com/watch/e6b703bb-a142-441e-9ff1-6d44527c75c9

**Comment by Xonshiz** [comment]
Can you run the tool with -v flag and upload the error log it generates.
Please do check and remove any credentials (if they appear in that file).

**Comment by jdelgado111** [comment]
Here's the log, not really sure if there's any credentials in this one that I should remove?

**Comment by Xonshiz** [comment]
Thanks for sharing the error log. Seems like file name is still not being changed. I'll reopen this and work on this.

**Comment by jdelgado111** [comment]
Thanks for fixing it!
